version: '3.4'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/reverse-proxy/index.html
  
  api:
    image: nginx:alpine
    container_name: api
    hostname: docker.app.api
    volumes:
      - ./api/index.html:/usr/share/nginx/html/index.html
  
  app-test-001:
    image: nginx:alpine
    container_name: app-test-001
    hostname: docker.app.test.first
    volumes:
      - ./app/app-test-001.html:/usr/share/nginx/html/index.html

  app-test-002:
    image: nginx:alpine
    container_name: app-test-002
    hostname: docker.app.test.second
    volumes:
      - ./app/app-test-002.html:/usr/share/nginx/html/index.html

  app-test-003:
    image: nginx:alpine
    container_name: app-test-003
    hostname: docker.app.test.third
    volumes:
      - ./app/app-test-003.html:/usr/share/nginx/html/index.html